# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\ui\getcon.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .icons import img_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 825)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Minimalistic-Flat-Modern-GUI-Template-master/Minimalistic-Flat-Modern-GUI-Template-master/images/Layout/frontpageAsset 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 90, 861, 591))
        self.widget.setObjectName("widget")
        self.leftpanel_2 = QtWidgets.QFrame(self.widget)
        self.leftpanel_2.setGeometry(QtCore.QRect(0, 0, 421, 591))
        self.leftpanel_2.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(116,116,116);")
        self.leftpanel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftpanel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftpanel_2.setObjectName("leftpanel_2")
        self.label = QtWidgets.QLabel(self.leftpanel_2)
        self.label.setGeometry(QtCore.QRect(0, 20, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("color:rgb(116, 116, 116);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(self.leftpanel_2)
        self.name.setGeometry(QtCore.QRect(10, 200, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setStyleSheet("border:none;\n"
"border-bottom: 4px solid rgb(115, 115, 115) ;")
        self.name.setObjectName("name")
        self.numerotravail = QtWidgets.QLineEdit(self.leftpanel_2)
        self.numerotravail.setGeometry(QtCore.QRect(10, 280, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numerotravail.setFont(font)
        self.numerotravail.setStyleSheet("border:none;\n"
"border-bottom: 4px solid rgb(115, 115, 115) ;\n"
"")
        # self.numerotravail.setEchoMode(QtWidgets.QLineEdit.Password)
        self.numerotravail.setObjectName("numerotravail")
        self.generatebutton = QtWidgets.QPushButton(self.leftpanel_2)
        self.generatebutton.setGeometry(QtCore.QRect(90, 500, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.generatebutton.setFont(font)
        self.generatebutton.setStyleSheet("background-color: rgb(116, 116, 116);\n"
"color: rgb(6, 6, 6);\n"
"border-radius: 20px;\n"
"padding: 5px;")
        self.generatebutton.setObjectName("generatebutton")
        self.label_4 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_4.setGeometry(QtCore.QRect(20, 350, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.services = QtWidgets.QComboBox(self.leftpanel_2)
        self.services.setGeometry(QtCore.QRect(10, 400, 341, 41))
        self.services.setObjectName("services")
        self.leftpanel = QtWidgets.QFrame(self.widget)
        self.leftpanel.setGeometry(QtCore.QRect(420, 0, 441, 591))
        self.leftpanel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url('D:/Python-tp-main/python/views/icons/backgroudlog.jpg'); \n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;")
        self.leftpanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftpanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftpanel.setObjectName("leftpanel")
        self.loginbutton = QtWidgets.QPushButton(self.leftpanel)
        self.loginbutton.setGeometry(QtCore.QRect(100, 500, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("background:rgb(116,116,116);\n"
"color: white;\n"
"border-radius: 20px;\n"
"padding: 5px;")
        self.loginbutton.setObjectName("loginbutton")
        self.label_5 = QtWidgets.QLabel(self.leftpanel)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: transparent ;\n"
"color: blue;")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "get connexion"))
        self.label_2.setText(_translate("MainWindow", "name"))
        self.label_3.setText(_translate("MainWindow", "nemero de travail"))
        self.generatebutton.setText(_translate("MainWindow", "get login id"))
        self.label_4.setText(_translate("MainWindow", "service"))
        self.services.setItemText(0, _translate("MainWindow", "service1"))
        self.services.setItemText(1, _translate("MainWindow", "service2"))
        self.loginbutton.setText(_translate("MainWindow", "login"))
        self.label_5.setText(_translate("MainWindow", "you have all ready an account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
